export const CATEGORIES = [
  'All', 'Pain Relief', 'Antibiotics', 'Eye Care', 'Vitamins',
  'Cold & Cough', 'Cardiac', 'Antacids', 'Skin Care', 'Diabetes',
];

export const MEDICINES = [
  {
    id: 'm1',
    productname: 'Dolo 650mg Strip Of 15 Tablets',
    price: 29.13, mrp: 34.27, offer: 15,
    description: '15 Tablets in Strip — Most trusted fever & pain relief',
    contains: 'Paracetamol (650mg)',
    category: 'Pain Relief',
    therapy: 'Analgesic/Antipyretic',
    uses: 'Fever and pain',
    sideEffects: 'Skin rash, itching (rare)',
    brand: 'DOLO', manufacturer: 'Micro Labs',
    prescription: false,
    img: 'https://cdn01.pharmeasy.in/dam/products/059346/dolo-650mg-strip-of-15-tablets-2-1653986150.jpg?dim=320x320&dpr=1&q=100',
    stock: 50,
  },
  {
    id: 'm2',
    productname: 'Dolo 500mg Tablet',
    price: 14.42, mrp: 16.96, offer: 15,
    description: '15 Tablets in Strip — Mild fever and pain',
    contains: 'Paracetamol (500mg)',
    category: 'Pain Relief',
    therapy: 'Analgesic/Antipyretic',
    uses: 'Fever and mild pain',
    sideEffects: 'Skin rash, blisters (rare)',
    brand: 'DOLO', manufacturer: 'Micro Labs',
    prescription: false,
    img: 'https://cdn01.pharmeasy.in/dam/products/192033/dolo-500mg-tablet-2-1641532606.jpg?dim=320x320&dpr=1&q=100',
    stock: 80,
  },
  {
    id: 'm3',
    productname: 'Ecosprin 75mg — 14 Tablets',
    price: 4.53, mrp: 5.33, offer: 15,
    description: '14 Tablets in Strip — Daily cardiac protection',
    contains: 'Aspirin (75mg)',
    category: 'Cardiac',
    therapy: 'Anti-Platelet',
    uses: 'Prevention of heart attack, stroke, angina',
    sideEffects: 'Indigestion, nausea (occasional)',
    brand: 'Ecosprin', manufacturer: 'USV Pvt Ltd',
    prescription: false,
    img: 'https://cdn01.pharmeasy.in/dam/products/064425/ecosprin-75mg-strip-of-14-tablets-1-1647434835.jpg?dim=320x320&dpr=1&q=100',
    stock: 120,
  },
  {
    id: 'm4',
    productname: 'Dorzox Eye Drops 5ml',
    price: 390.18, mrp: 459.03, offer: 15,
    description: '5ml Eye Drop in Bottle — Glaucoma management',
    contains: 'Dorzolamide (2%)',
    category: 'Eye Care',
    therapy: 'Glaucoma Drugs',
    uses: 'Raised eye pressure',
    sideEffects: 'Mild stinging (transient)',
    brand: 'DORZOX', manufacturer: 'Cipla Limited',
    prescription: true,
    img: 'https://cdn01.pharmeasy.in/dam/products/060175/dorzox-eye-drops-5ml-1-1641535227.jpg?dim=320x320&dpr=1&q=100',
    stock: 30,
  },
  {
    id: 'm5',
    productname: 'Teplota 100mg Syrup 15ml',
    price: 22.95, mrp: 27.00, offer: 15,
    description: '15ml Syrup — Paediatric fever relief',
    contains: 'Paracetamol (100mg/5ml)',
    category: 'Pain Relief',
    therapy: 'Analgesic/Antipyretic',
    uses: 'Fever in children',
    sideEffects: 'Rare at recommended doses',
    brand: 'TEPLOTA', manufacturer: 'Avighna Medicare',
    prescription: false,
    img: 'https://cdn01.pharmeasy.in/dam/products/W38967/teplota-100mg-bottle-of-15ml-syrup-1-1661333432.jpg?dim=320x320&dpr=1&q=100',
    stock: 60,
  },
  {
    id: 'm6',
    productname: 'Dolowin Plus Tablet (10)',
    price: 63.75, mrp: 75.00, offer: 15,
    description: '10 Tablets — Combined pain & inflammation relief',
    contains: 'Aceclofenac (100mg) + Paracetamol (500mg)',
    category: 'Pain Relief',
    therapy: 'Analgesic/Antipyretic',
    uses: 'Pain and inflammation',
    sideEffects: 'Nausea, stomach upset',
    brand: 'DOLOWIN PLUS', manufacturer: 'Micro Labs',
    prescription: true,
    img: 'https://cdn01.pharmeasy.in/dam/products/059610/dolowin-plus-tablet-2-1641535977.jpg?dim=320x320&dpr=1&q=100',
    stock: 40,
  },
  {
    id: 'm7',
    productname: 'Dolonex DT 20 — 15 Tablets',
    price: 183.45, mrp: 215.82, offer: 15,
    description: '15 Tablets — Arthritis & joint pain',
    contains: 'Piroxicam (20mg)',
    category: 'Pain Relief',
    therapy: 'Drugs for Osteoarthritis',
    uses: 'Pain and inflammation',
    sideEffects: 'Nausea, vomiting, stomach upset',
    brand: 'DOLONEX', manufacturer: 'Pfizer Ltd',
    prescription: true,
    img: 'https://cdn01.pharmeasy.in/dam/products/I04304/dolonex-dt-20-strip-of-15-tablets-2-1641536751.jpg?dim=320x320&dpr=1&q=100',
    stock: 25,
  },
  {
    id: 'm8',
    productname: 'Dolopar 650mg — 15 Tablets',
    price: 26.27, mrp: 30.91, offer: 15,
    description: '15 Tablets — Trusted pain and fever relief',
    contains: 'Paracetamol (650mg)',
    category: 'Pain Relief',
    therapy: 'Analgesic/Antipyretic',
    uses: 'Pain and fever',
    sideEffects: 'Skin rash, itching (rare)',
    brand: 'DOLOPAR', manufacturer: 'Micro Labs',
    prescription: false,
    img: 'https://cdn01.pharmeasy.in/dam/products/269216/dolopar-650mg-strip-of-15-tablets-1-1641533687.jpg?dim=320x320&dpr=1&q=100',
    stock: 70,
  },
  {
    id: 'm9',
    productname: 'Dologel Gel 15gm',
    price: 84.36, mrp: 99.25, offer: 15,
    description: '15g Mouth Gel — Mouth ulcer relief',
    contains: 'Choline Salicylate (8.7%) + Lidocaine (2%)',
    category: 'Skin Care',
    therapy: 'Topical Analgesia',
    uses: 'Mouth ulcers',
    sideEffects: 'Mild burning at application site',
    brand: 'DOLOGEL', manufacturer: "Dr Reddy's Laboratories",
    prescription: false,
    img: 'https://cdn01.pharmeasy.in/dam/products/059430/dologel-gel-15gm-1-1641535618.jpg?dim=320x320&dpr=1&q=100',
    stock: 35,
  },
  {
    id: 'm10',
    productname: 'Roseday Gold 20mg — 10 Capsules',
    price: 214.92, mrp: 252.85, offer: 15,
    description: '10 Capsules — Cholesterol + blood thinner combo',
    contains: 'Rosuvastatin (20mg) + Clopidogrel (75mg) + Aspirin (75mg)',
    category: 'Cardiac',
    therapy: 'Anti-Platelet & Hypolipidemic',
    uses: 'Heart attack, stroke prevention',
    sideEffects: 'Nausea, headache, muscle ache',
    brand: 'ROSEDAY', manufacturer: 'USV Pvt Ltd',
    prescription: true,
    img: 'https://cdn01.pharmeasy.in/dam/products/N11435/roseday-20mg-strip-of-15-tablets-6.1-1669357557.jpg?dim=320x320&dpr=1&q=100',
    stock: 20,
  },
  {
    id: 'm11',
    productname: 'Dolocold DS Syrup 60ml',
    price: 52.23, mrp: 61.45, offer: 15,
    description: '60ml Syrup — Cold and cough relief',
    contains: 'Chlorpheniramine (2mg) + Phenylephrine (5mg) + Paracetamol (250mg)',
    category: 'Cold & Cough',
    therapy: 'Cough Cold Preparation',
    uses: 'Common cold and cough',
    sideEffects: 'Headache, dizziness, drowsiness',
    brand: 'DOLOCOLD', manufacturer: 'Micro Labs',
    prescription: true,
    img: 'https://cdn01.pharmeasy.in/dam/products/G81368/dolocold-ds-syrup-60ml-1-1652180655.jpg?dim=320x320&dpr=1&q=100',
    stock: 45,
  },
  {
    id: 'm12',
    productname: 'Dolopar 250mg Suspension 60ml',
    price: 38.14, mrp: 44.35, offer: 15,
    description: '60ml Suspension — Paediatric pain & fever',
    contains: 'Paracetamol (250mg/5ml)',
    category: 'Pain Relief',
    therapy: 'Analgesic/Antipyretic',
    uses: 'Fever and pain in children',
    sideEffects: 'Rash, nausea (rare)',
    brand: 'DOLOPAR', manufacturer: 'Micro Labs',
    prescription: false,
    img: 'https://cdn01.pharmeasy.in/dam/products/059570/dolopar-250mg-suspension-60ml-2-1641535619.jpg?dim=320x320&dpr=1&q=100',
    stock: 55,
  },
];
